config/routes.rb
ADM::Application.routes.draw do

  match 'exposicion-de-carteles' => 'exposition_info#index', :as => :exposition_center
  
  match 'expositores' => 'exhibitors#index', :as => :exhibitors
  get "exhibitors/index"

  get "transportation/index"

  match 'inscripciones' => 'inscriptions#index', :as => :inscriptions_index
  
  resources :speakers
  
  resources :events

  match 'hoteles' => 'hotels#index', :as => :hotels
  match 'hoteles/nuevo' => 'hotels#new', :as => :new_hotel
  match 'hoteles/:id' => 'hotels#show', :as => :hotel
  match 'hoteles/:id/editar' => 'hotels#edit', :as => :edit_hotel
  resources :hotels

  match 'centro-de-exposiciones' => 'exposition_center#index', :as => :exposition_center
  
  get "ips/index"   
  
  match 'mapas' => 'maps#index', :as => :maps_index

  match 'informasion-de-contacto' => 'contact_info#index', :as => :contact_info_index
  
  match 'informasion-de-desarollo-web' => 'info#index', :as => :info_index

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'users/edit' => 'users#edit', :as => :edit_current_users

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'ips/:id', :to => 'ips#show'
  
  
  
  resources :ips

  resources :sessions

  resources :users

  match 'comite-organizador' => 'oc_members#index', :as => :oc_members
  match 'comite-organizador/nuevo' => 'oc_members#new', :as => :new_oc_member
  match 'comite-organizador/:id' => 'oc_members#show', :as => :oc_member
  match 'comite-organizador/:id/editar' => 'oc_members#edit', :as => :edit_oc_member
  resources :oc_members
  
  match 'comentarios' => 'comments#index', :as => :comments
  match 'comentarios/nuevo' => 'comments#new', :as => :new_comment
  match 'comentarios/:id' => 'comments#show', :as => :comment
  match 'comentarios/:id/editar' => 'comments#edit', :as => :edit_comment
  resources :comments
  
  mount Ckeditor::Engine => '/ckeditor'

  get "about_system/index"

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :email, :name, :title 
  validates  :comment, :email, :name, :title, :presence => true
  
  def to_param
    "#{id}-#{name.parameterize}"
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
   before_filter :login_required#, :except => [:new, :create, :show]
  # GET /comments
  # GET /comments.json
  def index
    not_allowed
    @comments = Comment.all

    #respond_to do |format|
    #format.html # index.html.erb
    #format.json { render json: @comments }
    #end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    @comment = Comment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # GET /comments/1/edit
  def edit
    @comment = Comment.find(params[:id])
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'El comentario fue creado exitosamente.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        flash[:error] = 'Por favor llene todos los campos requeridos.'
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /comments/1
  # PUT /comments/1.json
  def update
    @comment = Comment.find(params[:id])

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @comment, notice: 'El comentario fue actualizado exitosamente.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      flash[:notice] = 'El comentario fue eliminado exitosamente.'
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <%if @comment.errors.count > 1%>
        <h2><%=@comment.errors.count%> Errores prohibieron este comentario de ser guardado.</h2>
      <%else%>
        <h2>Un error prohibió este comentario de ser guardado.</h2>
      <%end%>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <%@num = 1%>
          <li><%=  msg %></li>
          <%@num = 1 + @num%>
        <% end %>
      </ul>
    </div>
  <% end %>

  <br />
  <%= f.label :name, "Nombre: *", :style => "color:black"%><br />
  <div class="field-holder">
    <%= f.text_field :name,  :id=> "commentInput" %><br />
  </div>
  <br />
  <%= f.label :email, "Correo Electrónico (No será mostrado): *", :style => "color:black"  %><br />
  <div class="field-holder">
    <%= f.email_field :email, :id=> "commentInput" %><br />
  </div>
  <br />
  <%= f.label :title, "Asunto: *", :style => "color:black" %><br />
  <div class="field-holder">
    <%= f.text_field :title, :id=> "commentInput"  %>
  </div>
  <br />
  <%= f.label :comment, "Comentario: *", :style => "color:black" %><br />
  <div class="field-holder">
    <%= f.cktext_area :comment, :toolbar => 'Easy', :width => 842, :height => 100 %>
  </div><br />

  <div class="actions">
    <%= f.submit "Aceptar", :title => "Enviar Comentario"%>
  </div>
<% end %>

app/views/comments/_index.html.erb
<div id="startcommets">
  <h1>Comentarios</h1>
</div>
<!--% @comments = Comment.paginate(:page => params[:page], :per_page => 8, :order => 'created_at DESC') %!-->
<% @comments = Comment.all%>
<% @comments.each do |comment| %>
  <div id ="comment"> 
    <div id="commentImage">
      <%=  image_tag("/assets/guess.gif", :size => '50x60') %>
    </div>
    <font color="black" style="margin-left:1.8em;"><b ><%= "Nombre: "%></b></font ><font color="#464646"><%= comment.name %></font><br />
    <font color="#45c7ee" style="margin-left:2.8em;" size="1px"><b ><%= comment.created_at.strftime("%d-%m-%Y %H:%M:%S") %></b></font><br />
    <font color="black" style="margin-left:1.8em;"><b ><%= "Comentario: "%></b></font><br />
    <font style="margin-left:1.8em;" color="#464646"><%= raw(comment.comment) %> </font>  
    <div id ="commentoptions">  
      <%= link_to 'Mostrar', comment_path(comment.id) + "#center", :title => "Mostrar comentario", :style => "color:#45c7ee" %> 
    </div>
  </div>
<% end %>
<!--%= will_paginate @comments, :class => "root"%!-->
<br/>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Title</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.email %></td>
    <td><%= comment.title %></td>
    <td><%= comment.comment %></td>
    <td><%= link_to 'Show', comment %></td>
    <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
    <td><%= link_to 'Destroy', comment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<div style="float: right; margin-top: 10px;">
  <%= button_tag 'Comentar', :class=>"commentbutton", :title => "Comentar",  :onclick => 'getform()', :id => "postgossip"%>
</div>

<script>
  var number = 1;
  function getform() {
    number++
    $("div#togglepostgossip").toggle();
    if (number%2 == 0){
      $('#postgossip').text("Ocultar");
    }else{
      $('#postgossip').text("Comentar");
    }
  }
</script>

<div style="margin-top:25px; display:none" id="togglepostgossip">
  <div id="newcommment">
    <h2 style="color: #45c7ee;">Comentar</h2>
    <%= render 'form'%>
  </div>
</div>

<%= render :partial => 'comments/index' %>

<div id ="alllinks" style="margin-bottom: 20px;" > 
  <%=link_to "Comentar", "#center", :onclick => 'getform()',%>
</div>

app/views/comments/show.html.erb
<h2>Comentario de <%= @comment.name %></h2>
<div id ="comment"> 
  <div id="commentImage">
        <%=  image_tag("/assets/guess.gif", :size => '50x60') %>
  </div>
    <font color="black" style="margin-left:1.8em;"><b ><%= "Nombre: "%></b></font ><font color="#464646"><%= @comment.name %></font><br />
    <font color="#45c7ee" style="margin-left:2.8em;" size="1px"><b ><%= @comment.created_at.strftime("%d-%m-%Y %H:%M:%S") %></b></font><br />
    <font color="black" style="margin-left:1.8em;"><b ><%= "Comentario: "%></b></font><br />
    <font style="margin-left:1.8em;" color="#464646"><%= raw(@comment.comment) %> </font>
</div>
<p >
  <div id="alllinks">
  <%= link_to 'Regresar', new_comment_path + "#center" %>         
    <!--%if current_user.user_type == "Administrator"%!-->
       <!--%= link_to 'Editar', edit_comment_path(@comment), :title => "Editar comentario"  %!--> 
       <!--%= link_to 'Eliminar', @comment, confirm: '¿Esta seguro que desea eliminar este comentario?', method: :delete, :title => "Eliminar comentario"  %!-->
    <!--%end%!-->
  </div>