config/routes.rb
ADM::Application.routes.draw do

  match 'exposicion-de-carteles' => 'exposition_info#index', :as => :exposition_center
  
  match 'expositores' => 'exhibitors#index', :as => :exhibitors
  get "exhibitors/index"

  get "transportation/index"

  match 'inscripciones' => 'inscriptions#index', :as => :inscriptions_index
  
  resources :speakers
  
  resources :events

  match 'hoteles' => 'hotels#index', :as => :hotels
  match 'hoteles/nuevo' => 'hotels#new', :as => :new_hotel
  match 'hoteles/:id' => 'hotels#show', :as => :hotel
  match 'hoteles/:id/editar' => 'hotels#edit', :as => :edit_hotel
  resources :hotels

  match 'centro-de-exposiciones' => 'exposition_center#index', :as => :exposition_center
  
  get "ips/index"   
  
  match 'mapas' => 'maps#index', :as => :maps_index

  match 'informasion-de-contacto' => 'contact_info#index', :as => :contact_info_index
  
  match 'informasion-de-desarollo-web' => 'info#index', :as => :info_index

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'users/edit' => 'users#edit', :as => :edit_current_users

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login
  
  match 'ips/:id', :to => 'ips#show'
  
  
  
  resources :ips

  resources :sessions

  resources :users

  match 'comite-organizador' => 'oc_members#index', :as => :oc_members
  match 'comite-organizador/nuevo' => 'oc_members#new', :as => :new_oc_member
  match 'comite-organizador/:id' => 'oc_members#show', :as => :oc_member
  match 'comite-organizador/:id/editar' => 'oc_members#edit', :as => :edit_oc_member
  resources :oc_members
  
  match 'comentarios' => 'comments#index', :as => :comments
  match 'comentarios/nuevo' => 'comments#new', :as => :new_comment
  match 'comentarios/:id' => 'comments#show', :as => :comment
  match 'comentarios/:id/editar' => 'comments#edit', :as => :edit_comment
  resources :comments
  
  mount Ckeditor::Engine => '/ckeditor'

  get "about_system/index"

  get "welcome/index"

  root :to => 'welcome#index'

end

app/models/oc_member.rb
class OcMember < ActiveRecord::Base
  attr_accessible :address1, :address2, :cellphone, :city, :email, :fax, :first_names, :last_names, :phone, :position, :state, :zipcode, :sex_type, :avatar
  
  has_attached_file :avatar, 
    :styles => { :large  => "600x600>" },
    :storage => :cloud_files,
    :cloudfiles_credentials =>  "#{Rails.root}/config/rackspace.yml",
    :container => 'ADM_members', 
    :ssl => true,
    :path => ":attachment/:id/:style/:normalized_file_name"

  Paperclip.interpolates :normalized_file_name do |attachment, style|
    attachment.instance.normalized_file_name
  end
  
  def fullname
    first_names + " " + last_names 
  end
  
  def to_param
    "#{id}-#{fullname.parameterize}"
  end

  def normalized_file_name
    "#{self.id}-#{self.avatar_file_name.gsub( /[^a-zA-Z0-9_\.]/, '_')}" 
  end  
  
end

app/controllers/oc_members_controller.rb
class OcMembersController < ApplicationController
  before_filter :login_required, :except => [:index, :show]
  # GET /oc_members
  # GET /oc_members.json
  def index
    @oc_members = OcMember.find(:all, :order => "created_at ASC")
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @oc_members }
    end
  end

  # GET /oc_members/1
  # GET /oc_members/1.json
  def show
    @oc_member = OcMember.find(params[:id])
    if @oc_member.sex_type == "Hombre"
      @Dr = "Dr. "
    else
      @Dr = "Dra. "
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @oc_member }
    end
  end

  # GET /oc_members/new
  # GET /oc_members/new.json
  def new
    @oc_member = OcMember.new
  end

  # GET /oc_members/1/edit
  def edit
    @oc_member = OcMember.find(params[:id])
  end

  # POST /oc_members
  # POST /oc_members.json
  def create
    #not_allowed
    @oc_member = OcMember.new(params[:oc_member])

    respond_to do |format|
      if @oc_member.save
        format.html { redirect_to @oc_member, notice: 'Oc member was successfully created.' }
        format.json { render json: @oc_member, status: :created, location: @oc_member }
      else
        format.html { render action: "new" }
        format.json { render json: @oc_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /oc_members/1
  # PUT /oc_members/1.json
  def update
    @oc_member = OcMember.find(params[:id])

    respond_to do |format|
      if @oc_member.update_attributes(params[:oc_member])
        format.html { redirect_to @oc_member, notice: 'Oc member was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @oc_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oc_members/1
  # DELETE /oc_members/1.json
  def destroy  
    @oc_member = OcMember.find(params[:id])
    @oc_member.destroy

    respond_to do |format|
      format.html { redirect_to oc_members_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/oc_members_helper.rb
module OcMembersHelper
end

app/views/oc_members/_form.html.erb
<%= form_for(@oc_member) do |f| %>
  <% if @oc_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oc_member.errors.count, "error") %> prohibited this oc_member from being saved:</h2>

      <ul>
      <% @oc_member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-holder">
    <%= f.label :first_names, "Nombres:"%><br />
    <%= f.text_field :first_names %>
  </div>
  <div class="field-holder">
    <%= f.label :last_names, "Apellidos:"%><br />
    <%= f.text_field :last_names %>
  </div>
  <div class="field-holder">
    <%= f.label :position, "Posición:" %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field-holder">
    <%= f.label :address1, "Dirección:" %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field-holder">
    <%= f.label :address2, "Colonia:" %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field-holder">
    <%= f.label :city, "Ciudad:" %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field-holder">
    <%= f.label :state, "Estado:" %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field-holder">
    <%= f.label :zipcode, "Código Postal:" %><br />
    <%= f.text_field :zipcode %>
  </div>
  <div class="field-holder">
    <%= f.label :phone, "Teléfono:" %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field-holder">
    <%= f.label :fax, "Numero de Fax:" %><br />
    <%= f.text_field :fax %>
  </div>
  <div class="field-holder">
    <%= f.label :cellphone, "Celular:" %><br />
    <%= f.text_field :cellphone %>
  </div>
  <div class="field-holder">
    <%= f.label :email, "Correo Electrónico:" %><br />
    <%= f.text_field :email %>
  </div>

    <div class="field-holder">
        <%= f.label :sex_type, "Sexo: "%><br />
        <%= f.select :sex_type, options_for_select([["Hombre"],["Mujer"]]) %>
    </div>

  <div class="field-holder">
    <%= f.label "Foto de Perfil:" %><br />
    <%= f.file_field :avatar%><br />
  </div>
  <div class="actions">
    <%= f.submit "Aceptar", :title => "Aceptar"%>
  </div>
<% end %>

app/views/oc_members/edit.html.erb
<h1>Editing oc_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @oc_member %> |
<%= link_to 'Back', oc_members_path %>

app/views/oc_members/index.html.erb
<div id="co_index">
  <h2 style="margin-bottom: 30px; text-align: center;">Integrantes del Comité Organizador</h2>
  <table style="margin-left: 20px">
    <% @oc_members.each do |oc_member| %>
      <% if oc_member.sex_type == "Hombre" %>
        <% @Dr = "Dr. " %>
      <% else %>
        <% @Dr = "Dra. " %>
      <% end %>
      <tr class="float_left_thumb">
        <td class="group" rel="group">
          <div style="margin-bottom: 24px ">
            <%=link_to image_tag(oc_member.avatar.url, :size => "136x136", :style => "padding-right: 8px" ), oc_member, :title => "Dar click para Mas información."%>
          </div>
          <div id="indexlinks1"><%=link_to oc_member.position + ": ", oc_member, :title => "Dar click para Mas información."%></div>
          <div id="indexlinks2"><%=link_to @Dr + oc_member.fullname, oc_member, :title => "Dar click para Mas información."%></div>
        </td>

      </tr>
    <%end%>
  </table>
</div>
<br />

<div id="alllinks">
  <% if logged_in? %>
    <%= link_to 'Registrar Nuevo Integrante', new_oc_member_path, :title => 'Registrar Nuevo Integrante' %> |
  <%end%>
  <%= link_to 'Inicio', root_path, :title => 'Inicio' %>
</div>

app/views/oc_members/new.html.erb
<h1>Registrar Nuevo Integrante del Comité Organizador</h1><br />

<%= render 'form' %>

<div id="alllinks" style="float: left;">
<%= link_to 'Regresar', oc_members_path %>
</div>

app/views/oc_members/show.html.erb
<link rel="stylesheet" type="text/css" href="/assets/js/fancybox/jquery.fancybox.css" media="screen">
<script type="text/javascript">
  $(document).ready(function() {
    $("a.group").fancybox();
  });
</script>

<div id ="comment" style="margin-bottom: 20px">    
  <h1 style="text-align:center; margin-bottom: 10px;"><%= @Dr + @oc_member.fullname%></h1>
  <div id="commentImage" style="margin-right: 58px; background-position: top" >
    <%=link_to image_tag(@oc_member.avatar.url, :size => "200x200"), @oc_member.avatar.url, :class =>"group", :title => @oc_member.position + ": " +  @oc_member.fullname%>
  </div>
  <div id="infocontainer">
    <br />
    <font color="#4682B4"><b ><%= "Posición: "%></b></font><%= @oc_member.position %><br />
    <font color="#4682B4"><b ><%= "Dirección: "%></b></font><%=@oc_member.address1 + " " + @oc_member.address2%><br />
    <span style="margin-left: 62px;"><%= "Cd. " + @oc_member.city + ", " + @oc_member.state + ". "%><br /></span>
    <span style="margin-left: 62px;"><%= "C.P. " + @oc_member.zipcode%><br /></span>
    <font color="#4682B4"><b ><%= "Teléfono: "%></b></font><%= @oc_member.phone %><br /> 
    <% unless @oc_member.fax %>
    <font color="#4682B4"><b ><%= "Numero de Fax: "%></b></font><%= @oc_member.fax %><br /> 
    <%end%>
    <font color="#4682B4"><b ><%= "Celular: "%></b></font><%= @oc_member.cellphone %><br /> 
    <font color="#4682B4"><b ><%= "Correo Electrónico: "%></b></font><%=mail_to @oc_member.email%> 
  </div>

<div id="alllinks">
  <% if logged_in? %>
    <%= link_to 'Editar', edit_oc_member_path(@oc_member.id), :title => "Editar integrante " + @oc_member.fullname%> |
    <%= link_to 'Eliminar', @oc_member, confirm: '¿Esta seguro de eliminar a este integrante del comité organizador?', method: :delete, :title => "Eliminar integrante " + @oc_member.fullname %> |
  <%end%>
    <div class="fb-like" data-href="http://www.dentaldeprovinciachihuahua2014.com/oc_members/<%= @oc_member.id %>" data-send="true" data-width="450" data-show-faces="true" data-colorscheme="light"></div>
    <%= link_to 'Regresar', oc_members_path, :title => "Regresar al Comité Organizador"%>
</div>
</div>